[tool]

[tool.poetry]
name = "qonwaygameoflife"
version = "0.1.0"
description = "Quantum game of life"
authors = ["Your Name <you@example.com>"]
[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.2"
#pygame = "^2.0.1"
qiskit = "^0.36.1"
